"""Surround game and training configuration constants."""

from pathlib import Path

# Game / simulation
GRID_ROWS = 18
GRID_COLS = 38
GAME_ROW_SLICE = slice(35, 198)
GAME_COL_SLICE = slice(4, 156)
EMPTY_CELL = 0
WALL_CELL = 1
EGO_CELL = 2
FRAME_SKIP = 8
DEBUG_STATE = False

# Env / run
DIFFICULTY = 0
MODE = 0
SEED = 0
MAX_CYCLES = 10_000

# Q-learning
ALPHA = 0.1
GAMMA = 0.99
EPSILON_START = 1.0
EPSILON_MIN = 0.05
EPSILON_DECAY_STEPS = 1000
EPISODES = 1_000_000
STEP_REWARD = 0.01
STATE_MODE = "state_tuple"
WINDOW_SIZE = 7

# Paths (Q-learning)
Q_TABLE_PATH = Path("surround/q_learning/q_table.json")
LOG_DIR = Path("runs/surround/ql_visits")

# DQN (input: stacked one-hot (DQN_FRAME_STACK, DQN_PREPROCESS_HEIGHT, DQN_PREPROCESS_WIDTH, 3))
DQN_FRAME_SKIP = 4
DQN_FRAME_STACK = 4
DQN_PREPROCESS_HEIGHT = 80
DQN_PREPROCESS_WIDTH = 80
BATCH_SIZE = 128
GAMMA_DQN = 0.99
EPS_START = 0.9
EPS_END = 0.01
EPS_DECAY_FRACTION = 0.5
TAU = 0.005
LR = 3e-4
MEMORY_CAPACITY = 10_000
NUM_EPISODES = 50_000
DQN_GAME_HEIGHT = GAME_ROW_SLICE.stop - GAME_ROW_SLICE.start
DQN_GAME_WIDTH = GAME_COL_SLICE.stop - GAME_COL_SLICE.start
N_ACTIONS = 4
VISUALIZE_DQN = True
DQN_LOG_DIR = Path("runs/surround_dqn_exp10")
DQN_EPISODE_VIDEO_FPS = 10
VISUALIZE_EPISODES = False
DQN_CHECKPOINT_DIR = DQN_LOG_DIR / "checkpoints"
DQN_CHECKPOINT_INTERVAL = 50
DQN_POLICY_NET_LATEST = DQN_CHECKPOINT_DIR / "policy_net_latest.pt"
DQN_POLICY_NET_BEST = DQN_CHECKPOINT_DIR / "policy_net_best.pt"
DQN_CHECKPOINT_METADATA = DQN_CHECKPOINT_DIR / "metadata.json"
